apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: seng4640
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: seng4640-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://172.27.202.96:27017/seng4640?replicaSet=rs0&directConnection=true"
            - name: MONGO_MAX_POOL_SIZE
              value: "20"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: LOG_LEVEL
              value: "warn"
            - name: PRODUCT_LIST_LIMIT_MAX
              value: "100"
            - name: APP_ENV
              value: "stg"
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
